Repository SSUMC-7th/Web_A, pull requests merged in 2024-11, with the labels that each got.

#26 [week6/mission] 회원가입 페이지 제작
  movie-project/.gitignore
  movie-project/README.md
  movie-project/index.html
  movie-project/package-lock.json
  movie-project/package.json
  movie-project/public/fonts/Pretendard-Bold.woff
  movie-project/public/fonts/Pretendard-Bold.woff2
  movie-project/public/fonts/Pretendard-Light.woff
  movie-project/public/fonts/Pretendard-Light.woff2
  movie-project/public/fonts/Pretendard-Regular.woff
  movie-project/public/fonts/Pretendard-Regular.woff2
  movie-project/public/vite.svg
  movie-project/src/App.jsx
  movie-project/src/GlobalStyles.js
  movie-project/src/api/axiosInstance.js
  movie-project/src/assets/img/category/nowPlaying.jpg
  movie-project/src/assets/img/category/popular.jpg
  movie-project/src/assets/img/category/topRated.jpg
  movie-project/src/assets/img/category/upcoming.jpg
  movie-project/src/assets/img/movieDetails/profile_path_null.jpg
  movie-project/src/components/button/Button.jsx
  movie-project/src/components/button/Button.module.css
  movie-project/src/components/index.js
  movie-project/src/components/navbar/Navbar.jsx
  movie-project/src/components/navbar/Navbar.module.css
  movie-project/src/components/sidebar/Sidebar.jsx
  movie-project/src/components/sidebar/Sidebar.module.css
  movie-project/src/config/eslint.config.js
  movie-project/src/config/vite.config.js
  movie-project/src/hooks/useCustomFetch.js
  movie-project/src/hooks/useForm.js
  movie-project/src/layout/rootLayout/RootLayout.jsx
  movie-project/src/layout/rootLayout/RootLayout.module.css
  movie-project/src/main.jsx
  movie-project/src/pages/category/Category.jsx
  movie-project/src/pages/category/Category.module.css
  movie-project/src/pages/error/Error.jsx
  movie-project/src/pages/error/Error.module.css
  movie-project/src/pages/home/Home.jsx
  movie-project/src/pages/home/Home.module.css
  movie-project/src/pages/index.js
  movie-project/src/pages/login/Login.jsx
  movie-project/src/pages/login/Login.module.css
  movie-project/src/pages/movie-pages/movie-categories/MovieCategories.module.css
  movie-project/src/pages/movie-pages/movie-categories/NowPlaying.jsx
  movie-project/src/pages/movie-pages/movie-categories/Popular.jsx
  movie-project/src/pages/movie-pages/movie-categories/TopRated.jsx
  movie-project/src/pages/movie-pages/movie-categories/Upcoming.jsx
  movie-project/src/pages/movie-pages/movie-details/MovieDetails.jsx
  movie-project/src/pages/movie-pages/movie-details/MovieDetails.module.css
  movie-project/src/pages/movie-pages/moviesCategory.jsx
  movie-project/src/pages/search/Search.jsx
  movie-project/src/pages/search/Search.module.css
  movie-project/src/pages/signup/Signup.jsx
  movie-project/src/pages/signup/Signup.module.css
  movie-project/utils/validate.js
Labels: Ch 5

#29 [week5/mission] Form Data 유효성 검사
  3/movie-frontend/.pnp.cjs
  3/movie-frontend/.yarn/install-state.gz
  3/movie-frontend/package.json
  3/movie-frontend/src/common/utils/cn.js
  3/movie-frontend/src/onboarding/component/text-field.jsx
  3/movie-frontend/src/onboarding/page/login/page.jsx
  3/movie-frontend/src/onboarding/page/register/register.jsx
  3/movie-frontend/yarn.lock
Labels: Ch 5

#36 [week7/mission] useQuery 활용, useInfiniteQuery활용, Pagination 기능 구현
  movie-project/package-lock.json
  movie-project/package.json
  movie-project/src/App.jsx
  movie-project/src/api/apiClient.js
  movie-project/src/api/endpoints/auth.js
  movie-project/src/api/endpoints/user.js
  movie-project/src/components/index.js
  movie-project/src/components/loading/Loading.jsx
  movie-project/src/components/loading/Loading.styles.js
  movie-project/src/components/movie-card/MovieCard.jsx
  movie-project/src/components/movie-card/MovieCard.styles.js
  movie-project/src/components/navbar/Navbar.jsx
  movie-project/src/components/search-movie-list/SearchMovieList.jsx
  movie-project/src/components/search-movie-list/SearchMovieList.styles.js
  movie-project/src/contexts/AuthContext.jsx
  movie-project/src/hooks/queries/useFetchMovieCredit.js
  movie-project/src/hooks/queries/useFetchMovieDetails.js
  movie-project/src/hooks/queries/useFetchMovieSearchResult.js
  movie-project/src/hooks/queries/useFetchMovies.js
  movie-project/src/hooks/queries/useFetchUserData.js
  movie-project/src/hooks/useCustomFetchMovie.js
  movie-project/src/pages/home/Home.jsx
  movie-project/src/pages/home/Home.styles.js
  movie-project/src/pages/login/Login.jsx
  movie-project/src/pages/movie-pages/movie-categories/NowPlaying.jsx
  movie-project/src/pages/movie-pages/movie-categories/Popular.jsx
  movie-project/src/pages/movie-pages/movie-categories/TopRated.jsx
  movie-project/src/pages/movie-pages/movie-categories/Upcoming.jsx
  movie-project/src/pages/movie-pages/movie-details/MovieDetails.jsx
  movie-project/src/pages/movie-pages/movie-details/MovieDetails.styles.js
  movie-project/src/pages/movie-pages/moviesCategory.jsx
Labels: Ch 7

#46 [week9/mission] redux-toolkit 활용 UMC PlayList 제작, Modal Slice 활용하여, 모…
  play-list/.eslintrc.cjs
  play-list/.gitignore
  play-list/index.html
  play-list/package-lock.json
  play-list/package.json
  play-list/postcss.config.cjs
  play-list/src/App.tsx
  play-list/src/components/Modal/Modal.styles.ts
  play-list/src/components/Modal/Modal.tsx
  play-list/src/components/PlayListItem/PlayListItem.styles.ts
  play-list/src/components/PlayListItem/PlayListItem.tsx
  play-list/src/components/index.ts
  play-list/src/data/cartItems.ts
  play-list/src/data/icons.tsx
  play-list/src/hooks/useRedux.ts
  play-list/src/main.tsx
  play-list/src/pages/PlayList/PlayList.styles.ts
  play-list/src/pages/PlayList/PlayList.tsx
  play-list/src/redux/cartSlice.ts
  play-list/src/redux/modalSlice.ts
  play-list/src/redux/store.ts
  play-list/src/styles/GlobalStyles.ts
  play-list/src/types/cartItem.ts
  play-list/src/vite-env.d.ts
  play-list/tailwind.config.js
  play-list/tsconfig.json
  play-list/tsconfig.node.json
  play-list/vite.config.ts
Labels: Ch 9
