Repository SSUMC-7th/Web_A, pull requests merged in 2024-10, with the labels that each got.

#14 [week2/mission] Todo List(HTML, CSS, JS)
  index.html
  index.js
  style.css
Labels: Ch 1

#13 [week2/mission] Todo List(CSS), 영화 컴포넌트
  2/movie-component/.gitignore
  2/movie-component/README.md
  2/movie-component/eslint.config.js
  2/movie-component/index.html
  2/movie-component/package.json
  2/movie-component/public/vite.svg
  2/movie-component/src/App.css
  2/movie-component/src/App.jsx
  2/movie-component/src/assets/react.svg
  2/movie-component/src/components/movie-card/index.css
  2/movie-component/src/components/movie-card/index.jsx
  2/movie-component/src/index.css
  2/movie-component/src/main.jsx
  2/movie-component/src/mocks/movie.js
  2/movie-component/vite.config.js
  2/movie-component/yarn.lock
  2/to-do-list/.gitignore
  2/to-do-list/README.md
  2/to-do-list/eslint.config.js
  2/to-do-list/index.html
  2/to-do-list/package.json
  2/to-do-list/public/vite.svg
  2/to-do-list/src/App.css
  2/to-do-list/src/App.jsx
  2/to-do-list/src/assets/react.svg
  2/to-do-list/src/components/custom_button.jsx
  2/to-do-list/src/components/custom_textfield.jsx
  2/to-do-list/src/index.css
  2/to-do-list/src/main.jsx
  2/to-do-list/vite.config.js
  2/to-do-list/yarn.lock
Labels: Ch 2

#11 [week2/mission] Todo List(HTML, CSS, JS)
  1/index.html
  1/index.js
  1/style.css
Labels: Ch 1

#12 [week2/mission] Todo List(CSS), 영화 컴포넌트
  2/movie-project/.gitignore
  2/movie-project/README.md
  2/movie-project/eslint.config.js
  2/movie-project/index.html
  2/movie-project/package-lock.json
  2/movie-project/package.json
  2/movie-project/public/vite.svg
  2/movie-project/src/App.css
  2/movie-project/src/App.jsx
  2/movie-project/src/components/MovieList.jsx
  2/movie-project/src/index.css
  2/movie-project/src/main.jsx
  2/movie-project/src/mocks/movie.js
  2/movie-project/vite.config.js
  2/to-do-list/.gitignore
  2/to-do-list/README.md
  2/to-do-list/eslint.config.js
  2/to-do-list/index.html
  2/to-do-list/package-lock.json
  2/to-do-list/package.json
  2/to-do-list/public/vite.svg
  2/to-do-list/src/App.css
  2/to-do-list/src/App.jsx
  2/to-do-list/src/components/Button.jsx
  2/to-do-list/src/components/Input.jsx
  2/to-do-list/src/components/ToDoList.jsx
  2/to-do-list/src/index.css
  2/to-do-list/src/main.jsx
  2/to-do-list/vite.config.js
Labels: Ch 2

#15 [week2/mission] Todo List(CSS), 영화 컴포넌트
  2/movie-week2/.gitignore
  2/movie-week2/README.md
  2/movie-week2/package-lock.json
  2/movie-week2/package.json
  2/movie-week2/public/favicon.ico
  2/movie-week2/public/index.html
  2/movie-week2/public/logo192.png
  2/movie-week2/public/logo512.png
  2/movie-week2/public/manifest.json
  2/movie-week2/public/robots.txt
  2/movie-week2/src/App.css
  2/movie-week2/src/App.js
  2/movie-week2/src/App.test.js
  2/movie-week2/src/Components/Movie.jsx
  2/movie-week2/src/index.css
  2/movie-week2/src/index.js
  2/movie-week2/src/logo.svg
  2/movie-week2/src/movieDummy.js
  2/movie-week2/src/reportWebVitals.js
  2/movie-week2/src/setupTests.js
  save/.gitignore
  save/README.md
  save/eslint.config.js
  save/index.html
  save/package.json
  save/public/vite.svg
  save/src/App.css
  save/src/App.jsx
  save/src/Button.jsx
  save/src/Input.jsx
  save/src/assets/react.svg
  save/src/index.css
  save/src/main.jsx
  save/vite.config.js
  save/yarn.lock
Labels: Ch 2

#16 [week3/mission] 영화 사이트 제작
  3/movie-project/.gitignore
  3/movie-project/README.md
  3/movie-project/index.html
  3/movie-project/package-lock.json
  3/movie-project/package.json
  3/movie-project/public/vite.svg
  3/movie-project/services/api.js
  3/movie-project/src/App.css
  3/movie-project/src/App.jsx
  3/movie-project/src/GlobalStyles.js
  3/movie-project/src/assets/forest.jpg
  3/movie-project/src/components/Button.jsx
  3/movie-project/src/components/Navbar.jsx
  3/movie-project/src/components/Sidebar.jsx
  3/movie-project/src/components/index.js
  3/movie-project/src/config/eslint.config.js
  3/movie-project/src/config/vite.config.js
  3/movie-project/src/index.css
  3/movie-project/src/layout/RootLayout.jsx
  3/movie-project/src/main.jsx
  3/movie-project/src/pages/Category.jsx
  3/movie-project/src/pages/Error.jsx
  3/movie-project/src/pages/Home.jsx
  3/movie-project/src/pages/Login.jsx
  3/movie-project/src/pages/Movies.jsx
  3/movie-project/src/pages/Search.jsx
  3/movie-project/src/pages/SignUp.jsx
  3/movie-project/src/pages/index.js
Labels: Ch 3

#18 [week3/mission] 영화 사이트 제작
  new3/movie-project/.gitignore
  new3/movie-project/README.md
  new3/movie-project/eslint.config.js
  new3/movie-project/index.html
  new3/movie-project/package.json
  new3/movie-project/public/vite.svg
  new3/movie-project/src/App.css
  new3/movie-project/src/App.jsx
  new3/movie-project/src/GlobalStyle.js
  new3/movie-project/src/assets/react.svg
  new3/movie-project/src/components/CustomButton.jsx
  new3/movie-project/src/components/IconButton.jsx
  new3/movie-project/src/components/NavBar.jsx
  new3/movie-project/src/components/SideBar.jsx
  new3/movie-project/src/image/cinna.png
  new3/movie-project/src/image/han.jpg
  new3/movie-project/src/image/pocha.jpg
  new3/movie-project/src/image/pompom.png
  new3/movie-project/src/index.css
  new3/movie-project/src/main.jsx
  new3/movie-project/src/pages/Category.jsx
  new3/movie-project/src/pages/Home.jsx
  new3/movie-project/src/pages/Login.jsx
  new3/movie-project/src/pages/Movies.jsx
  new3/movie-project/src/pages/NotFound.jsx
  new3/movie-project/src/pages/RootLayout.jsx
  new3/movie-project/src/pages/Search.jsx
  new3/movie-project/src/pages/SignIn.jsx
  new3/movie-project/vite.config.js
  new3/movie-project/yarn.lock
Labels: Ch 3

#19 [week3/mission] 영화 사이트 제작
  03/.env
  03/.gitignore
  03/README.md
  03/eslint.config.js
  03/index.html
  03/package-lock.json
  03/package.json
  03/public/vite.svg
  03/src/App.css
  03/src/App.jsx
  03/src/assets/movie1.jpg
  03/src/assets/movie2.jpg
  03/src/assets/movie3.jpg
  03/src/assets/movie4.jpg
  03/src/assets/react.svg
  03/src/components/Card/Card.jsx
  03/src/components/custom-button.jsx
  03/src/components/navbar.jsx
  03/src/components/sidebar.jsx
  03/src/index.css
  03/src/layout/root-layout.jsx
  03/src/main.jsx
  03/src/mocks/movies.js
  03/src/pages/HomePage.jsx
  03/src/pages/LoginPage.jsx
  03/src/pages/MoviesPage/MoviesPage.jsx
  03/src/pages/MoviesPage/movies.style.js
  03/src/pages/NowPlayingPage.jsx
  03/src/pages/PopularPage.jsx
  03/src/pages/SearchPage/SearchPage.jsx
  03/src/pages/SignupPage.jsx
  03/src/pages/TopRatedPage.jsx
  03/src/pages/UpcomingPage.jsx
  03/src/pages/not-found.jsx
  03/vite.config.js
  03/yarn.lock
Labels: Ch 3

#23 [week4/mission]Custom Hooks 실습 , 영화 상세 페이지 제작
  3/movie-frontend/.gitignore
  3/movie-frontend/.pnp.cjs
  3/movie-frontend/.pnp.loader.mjs
  3/movie-frontend/.yarn/install-state.gz
  3/movie-frontend/eslint.config.js
  3/movie-frontend/package.json
  3/movie-frontend/postcss.config.js
  3/movie-frontend/src/App.jsx
  3/movie-frontend/src/common/api/client.js
  3/movie-frontend/src/common/component/background.js
  3/movie-frontend/src/common/component/buttons/button.jsx
  3/movie-frontend/src/common/component/buttons/icon-button.jsx
  3/movie-frontend/src/common/component/flex.jsx
  3/movie-frontend/src/common/component/icon-button.jsx
  3/movie-frontend/src/common/component/switch.jsx
  3/movie-frontend/src/common/component/text-box.jsx
  3/movie-frontend/src/common/component/title.js
  3/movie-frontend/src/common/layout/navbar.jsx
  3/movie-frontend/src/common/layout/sidebar.jsx
  3/movie-frontend/src/common/utils/cn.ts
  3/movie-frontend/src/index.css
  3/movie-frontend/src/movie/api/get-movie-data.js
  3/movie-frontend/src/movie/api/get/get-movie-credits.js
  3/movie-frontend/src/movie/api/get/get-movie-data.js
  3/movie-frontend/src/movie/api/get/get-movie-detail.js
  3/movie-frontend/src/movie/component/category-card.jsx
  3/movie-frontend/src/movie/component/loading-card.jsx
  3/movie-frontend/src/movie/component/post-card.jsx
  3/movie-frontend/src/movie/container/detail-credit-section.jsx
  3/movie-frontend/src/movie/container/detail-top-section.jsx
  3/movie-frontend/src/movie/hook/api/get/use-get-movie-credits.js
  3/movie-frontend/src/movie/hook/api/get/use-get-movie-data.js
  3/movie-frontend/src/movie/hook/api/get/use-get-movie-detail.js
  3/movie-frontend/src/movie/page/category/page.jsx
  3/movie-frontend/src/movie/page/movie/category/page.jsx
  3/movie-frontend/src/movie/page/movie/detail/page.jsx
  3/movie-frontend/src/movie/page/movie/page.jsx
  3/movie-frontend/src/movie/page/now-playing/page.jsx
  3/movie-frontend/src/movie/page/popular/page.jsx
  3/movie-frontend/src/movie/page/search/page.jsx
  3/movie-frontend/src/movie/page/top-rated/page.jsx
  3/movie-frontend/src/movie/page/up-coming/page.jsx
  3/movie-frontend/src/onboarding/page/login/page.jsx
  3/movie-frontend/src/onboarding/page/register/register.jsx
  3/movie-frontend/tailwind.config.js
  3/movie-frontend/vite.config.js
  3/movie-frontend/yarn.lock
Labels: Ch 4

#24 [week4/mission]Custom Hooks 실습 , 영화 상세 페이지 제작
  .env
  .gitignore
  eslint.config.js
  index.html
  package.json
  public/vite.svg
  src/App.css
  src/App.jsx
  src/GlobalStyle.js
  src/apis/axios-instance.js
  src/assets/react.svg
  src/components/CustomButton.jsx
  src/components/IconButton.jsx
  src/components/NavBar.jsx
  src/components/SideBar.jsx
  src/hooks/useCustomFetch.js
  src/hooks/useMovieDetails.js
  src/image/cinna.png
  src/image/han.jpg
  src/image/pocha.jpg
  src/image/pompom.png
  src/index.css
  src/main.jsx
  src/pages/Category.jsx
  src/pages/Home.jsx
  src/pages/Login.jsx
  src/pages/MovieDetail.jsx
  src/pages/Movies.jsx
  src/pages/NotFound.jsx
  src/pages/RootLayout.jsx
  src/pages/Search.jsx
  src/pages/SignIn.jsx
  vite.config.js
  yarn.lock
Labels: Ch 4

#22 [week4/mission]Custom Hooks 실습 , 영화 상세 페이지 제작
  05/.gitignore
  05/README.md
  05/eslint.config.js
  05/index.html
  05/package-lock.json
  05/package.json
  05/public/vite.svg
  05/src/App.css
  05/src/App.jsx
  05/src/apis/axios-instance.js
  05/src/assets/movie1.jpg
  05/src/assets/movie2.jpg
  05/src/assets/movie3.jpg
  05/src/assets/movie4.jpg
  05/src/assets/react.svg
  05/src/components/Card/Card.jsx
  05/src/components/custom-button.jsx
  05/src/components/navbar.jsx
  05/src/components/sidebar.jsx
  05/src/hooks/useCustomFetch.js
  05/src/index.css
  05/src/layout/root-layout.jsx
  05/src/main.jsx
  05/src/pages/HomePage.jsx
  05/src/pages/LoginPage.jsx
  05/src/pages/MovieDetailPage.jsx
  05/src/pages/MoviesPage/MoviesPage.jsx
  05/src/pages/NowPlayingPage.jsx
  05/src/pages/PopularPage.jsx
  05/src/pages/SearchPage/SearchPage.jsx
  05/src/pages/SignupPage.jsx
  05/src/pages/TopRatedPage.jsx
  05/src/pages/UpcomingPage.jsx
  05/src/pages/not-found.jsx
  05/vite.config.js
  05/yarn.lock
Labels: Ch 4
